# Data Cleaning
## Lagos & Abuja Rent Prediction
## 3MTT Capstone Project

In [1]:
import pandas as pd

houses = {
    "Bedrooms": [2, 4, 1],
    "Bathrooms": [3, 5, 1],
    "Location": ["Lekki", "Maitama", "Yaba"],
    "Rent": [3500000, 9000000, 1200000]
}

df = pd.DataFrame(houses)

df

   Bedrooms  Bathrooms Location     Rent
0         2          3    Lekki  3500000
1         4          5  Maitama  9000000
2         1          1     Yaba  1200000

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/nigeria-rent.csv")

In [4]:
df

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
0,Newly Built 4 Bedroom Semi Detached House With Bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
1,Superb 4 Bedroom Semi Detached Duplex With Bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
2,Furnished 2 Bedroom Terrace Duplex For Rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets
3,2 Bedroom Apartment For Rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets
4,?? Brand New 2 Bedroom Flat For Rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets
...,...,...,...,...,...,...,...,...,...,...
98075,4 Bedroom Duplex In Serene Neighborhood,4 BEDROOM HOUSE FOR RENT,Akala Akobo Ibadan Oyo,"900,000",0,0,0,4 beds,4 baths,4 Toilets
98076,Lovely Built 3 Bedroom Flats Self Compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets
98077,Executive 2 Bedroom Flat,2 BEDROOM BLOCKS OF FLATS FOR RENT,By Sterling Bank Magboro Obafemi Owode Ogun,"330,000",0,0,1,2 beds,3 baths,3 Toilets
98078,Executive Brand New 2 Bedroom Flat All Rooms E...,2 BEDROOM BLOCKS OF FLATS FOR RENT,Arepo Arepo Arepo Ogun,"400,000",0,1,1,2 beds,3 baths,3 Toilets
98079,3 Bedroom Flat All Ensuit,3 BEDROOM BLOCKS OF FLATS FOR RENT,"3bedroom Flat At Jeje Area, Apete.all Rooms En...","150,000",0,0,0,3 beds,3 baths,3 Toilets

In [5]:
df.head()

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
0,Newly Built 4 Bedroom Semi Detached House With Bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
1,Superb 4 Bedroom Semi Detached Duplex With Bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
2,Furnished 2 Bedroom Terrace Duplex For Rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets
3,2 Bedroom Apartment For Rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets
4,?? Brand New 2 Bedroom Flat For Rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets

In [6]:
df.tail()

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
98075,4 Bedroom Duplex In Serene Neighborhood,4 BEDROOM HOUSE FOR RENT,Akala Akobo Ibadan Oyo,"900,000",0,0,0,4 beds,4 baths,4 Toilets
98076,Lovely Built 3 Bedroom Flats Self Compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets
98077,Executive 2 Bedroom Flat,2 BEDROOM BLOCKS OF FLATS FOR RENT,By Sterling Bank Magboro Obafemi Owode Ogun,"330,000",0,0,1,2 beds,3 baths,3 Toilets
98078,Executive Brand New 2 Bedroom Flat All Rooms E...,2 BEDROOM BLOCKS OF FLATS FOR RENT,Arepo Arepo Arepo Ogun,"400,000",0,1,1,2 beds,3 baths,3 Toilets
98079,3 Bedroom Flat All Ensuit,3 BEDROOM BLOCKS OF FLATS FOR RENT,"3bedroom Flat At Jeje Area, Apete.all Rooms En...","150,000",0,0,0,3 beds,3 baths,3 Toilets

In [7]:
df.shape

(98080, 10)

In [8]:
df.columns

Index(['Title', 'More Info', 'Location', 'Price', 'Serviced', 'Newly Built',
       'Furnished', 'Bedrooms', 'Bathrooms', 'Toilets'],
      dtype='str')

In [9]:
df.dtypes

Title            str
More Info        str
Location         str
Price            str
Serviced       int64
Newly Built    int64
Furnished      int64
Bedrooms         str
Bathrooms        str
Toilets          str
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98080 entries, 0 to 98079
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        98079 non-null  str
 1   More Info    98080 non-null  str
 2   Location     98080 non-null  str
 3   Price        98080 non-null  str
 4   Serviced     98080 non-null  int64
 5   Newly Built  98080 non-null  int64
 6   Furnished    98080 non-null  int64
 7   Bedrooms     98080 non-null  str
 8   Bathrooms    98080 non-null  str
 9   Toilets      98080 non-null  str
dtypes: int64(3), str(7)
memory usage: 7.5 MB

In [11]:
df.isnull().sum()

Title          1
More Info      0
Location       0
Price          0
Serviced       0
Newly Built    0
Furnished      0
Bedrooms       0
Bathrooms      0
Toilets        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(4122)

In [13]:
df.sample(10)

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
55162,Beautiful 2bedroom Apartment,2 BEDROOM FLAT / APARTMENT FOR RENT,Dopemu Alimosho Lagos,"500,000",0,0,0,2 beds,0 baths,0 Toilets
65643,Clean Mini Flat,1 BEDROOM MINI FLAT FOR RENT,Marsha Kilo Marsha Surulere Lagos,"500,000/year",0,0,0,1 beds,1 baths,1 Toilets
5942,1 Bedroom Flat,1 BEDROOM FLAT / APARTMENT FOR RENT,Asokoro Asokoro Abuja,"1,700,000/year",0,0,0,1 beds,1 baths,0 Toilets
77809,Newly Built 4 Bedroom Standard Detached Duplex,4 BEDROOM HOUSE FOR RENT,Off 4th Avenue Gwarinpa Abuja,"4,500,000",0,0,0,4 beds,4 baths,5 Toilets
40425,Lovely 2 Bedroom Flat,2 BEDROOM FLAT / APARTMENT FOR RENT,By Domino's Pizza Agungi Lekki Lagos,"2,500,000/year",0,0,0,2 beds,3 baths,3 Toilets
97128,A Room Self Contain At Onipetesi Estate Mangor...,1 BEDROOM SELF CONTAIN FOR RENT,Onipetesi Estate Mangoro Ikeja Lagos,"150,000",0,0,0,1 beds,1 baths,1 Toilets
45256,Nice Mini Flat,1 BEDROOM FLAT / APARTMENT FOR RENT,Okupe Estate Mende Maryland Lagos,"1,300,000/year",0,0,0,1 beds,1 baths,1 Toilets
97406,Clean Renovated 2 Bedroom Flat All Tiles Floor...,2 BEDROOM BLOCKS OF FLATS FOR RENT,Iyana Ipaja Iyana Ipaja Ipaja Lagos,"400,000",0,0,0,2 beds,3 baths,3 Toilets
37033,Mini Flat,1 BEDROOM FLAT / APARTMENT FOR RENT,Isheri North Estate (new Magodo) Isheri North ...,"550,000/year",0,1,0,1 beds,1 baths,2 Toilets
35637,Mini Flat,1 BEDROOM FLAT / APARTMENT FOR RENT,Awoyaya Ajah Lagos,"550,000/year",0,1,0,1 beds,1 baths,1 Toilets

In [14]:
df["Price"].head(10)

0    5,000,000/year
1    5,000,000/year
2         3,500,000
3         2,700,000
4         5,000,000
5         4,000,000
6         6,500,000
7         6,500,000
8         3,500,000
9    4,000,000/year
Name: Price, dtype: str

In [17]:
## IN ORDER NOT TO CLEAN ORIGINAL DATASET, I CREATED A WORKING COPY

In [18]:
# Create a copy of the original dataset
df_clean = df.copy()

In [19]:
df

,Title,More Info,Location,Price,Serviced,Newly Built,Furnished,Bedrooms,Bathrooms,Toilets
0,Newly Built 4 Bedroom Semi Detached House With Bq,4 BEDROOM HOUSE FOR RENT,"White Oak Estate, Ologolo Opp. Agungi, Ologolo...","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
1,Superb 4 Bedroom Semi Detached Duplex With Bq,4 BEDROOM HOUSE FOR RENT,"Hrc Estate Beside Vgc Estate, Vgc Lekki Lagos","5,000,000/year",0,1,0,4 beds,4 baths,5 Toilets
2,Furnished 2 Bedroom Terrace Duplex For Rent !!!,2 BEDROOM HOUSE FOR RENT,Osapa London Lekki Lagos,"3,500,000",1,0,0,2 beds,3 baths,3 Toilets
3,2 Bedroom Apartment For Rent,2 BEDROOM HOUSE FOR RENT,Ologolo Lekki Lagos,"2,700,000",1,1,0,2 beds,3 baths,3 Toilets
4,?? Brand New 2 Bedroom Flat For Rent!!! (groun...,2 BEDROOM HOUSE FOR RENT,Mojisola Onikoyi Ikoyi Lagos,"5,000,000",1,1,0,2 beds,3 baths,3 Toilets
...,...,...,...,...,...,...,...,...,...,...
98075,4 Bedroom Duplex In Serene Neighborhood,4 BEDROOM HOUSE FOR RENT,Akala Akobo Ibadan Oyo,"900,000",0,0,0,4 beds,4 baths,4 Toilets
98076,Lovely Built 3 Bedroom Flats Self Compound,3 BEDROOM SELF CONTAIN FOR RENT,Oluwaga Road. Baruwa Ipaja Lagos,"500,000",0,1,1,3 beds,4 baths,4 Toilets
98077,Executive 2 Bedroom Flat,2 BEDROOM BLOCKS OF FLATS FOR RENT,By Sterling Bank Magboro Obafemi Owode Ogun,"330,000",0,0,1,2 beds,3 baths,3 Toilets
98078,Executive Brand New 2 Bedroom Flat All Rooms E...,2 BEDROOM BLOCKS OF FLATS FOR RENT,Arepo Arepo Arepo Ogun,"400,000",0,1,1,2 beds,3 baths,3 Toilets
98079,3 Bedroom Flat All Ensuit,3 BEDROOM BLOCKS OF FLATS FOR RENT,"3bedroom Flat At Jeje Area, Apete.all Rooms En...","150,000",0,0,0,3 beds,3 baths,3 Toilets

In [20]:
df_clean["Price"].head(10)

0    5,000,000/year
1    5,000,000/year
2         3,500,000
3         2,700,000
4         5,000,000
5         4,000,000
6         6,500,000
7         6,500,000
8         3,500,000
9    4,000,000/year
Name: Price, dtype: str

In [21]:
df_clean["Price"] = (
    df_clean["Price"]
    .astype(str)
    .str.replace("₦", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace("/year", "", regex=False)
    .str.strip()
)

In [22]:
df_clean["Price"] = pd.to_numeric(df_clean["Price"], errors="coerce")

In [23]:
df_clean["Price"].head(10)

0    5000000.0
1    5000000.0
2    3500000.0
3    2700000.0
4    5000000.0
5    4000000.0
6    6500000.0
7    6500000.0
8    3500000.0
9    4000000.0
Name: Price, dtype: float64

In [24]:
df_clean["Price"].dtype

dtype('float64')

In [25]:
df_clean["Price"].isnull().sum()

np.int64(855)

In [26]:
df_clean.to_csv("../data/processed/rent_clean_v1.csv", index=False)

In [27]:
df_clean["Bedrooms"].head(20)

0     4 beds
1     4 beds
2     2 beds
3     2 beds
4     2 beds
5     4 beds
6     3 beds
7     3 beds
8     3 beds
9     5 beds
10    5 beds
11    5 beds
12    3 beds
13    5 beds
14    2 beds
15    4 beds
16    4 beds
17    3 beds
18    4 beds
19    3 beds
Name: Bedrooms, dtype: str

In [28]:
df_clean["Bedrooms"].unique()

<StringArray>
[ '4 beds',  '2 beds',  '3 beds',  '5 beds',  '0 beds',  '1 beds',  '6 beds',
   ' beds',  '7 beds', '10 beds',  '8 beds',  '9 beds']
Length: 12, dtype: str

In [29]:
df_clean["Bedrooms"].value_counts()

Bedrooms
3 beds     24848
2 beds     22174
1 beds     19765
4 beds     12513
0 beds     10516
5 beds      4063
 beds       3172
6 beds       483
10 beds      254
7 beds       148
8 beds       104
9 beds        40
Name: count, dtype: int64

In [30]:
df_clean["Bathrooms"].unique()

<StringArray>
[ '4 baths',  '3 baths',  '5 baths',  '6 baths',  '2 baths',  '0 baths',
  '1 baths',  '7 baths',   ' baths', '10 baths',  '8 baths',  '9 baths']
Length: 12, dtype: str

In [31]:
df_clean["Toilets"].unique()

<StringArray>
[ '5 Toilets',  '3 Toilets',  '4 Toilets',  '6 Toilets',  '7 Toilets',
  '2 Toilets',  '0 Toilets',  '1 Toilets',  '8 Toilets',   ' Toilets',
 '10 Toilets',  '9 Toilets']
Length: 12, dtype: str

In [32]:
df_clean["Bedrooms"] = df_clean["Bedrooms"].str.extract(r"(\d+)")

In [33]:
df_clean["Bedrooms"] = pd.to_numeric(df_clean["Bedrooms"], errors="coerce")

In [34]:
df_clean["Bedrooms"].head(10)

0    4.0
1    4.0
2    2.0
3    2.0
4    2.0
5    4.0
6    3.0
7    3.0
8    3.0
9    5.0
Name: Bedrooms, dtype: float64

In [35]:
df_clean["Bedrooms"].dtype

dtype('float64')

In [36]:
df_clean["Bathrooms"] = df_clean["Bathrooms"].str.extract(r"(\d+)")

In [37]:
df_clean["Bathrooms"] = pd.to_numeric(df_clean["Bathrooms"], errors="coerce")

In [38]:
df_clean["Toilets"] = df_clean["Toilets"].str.extract(r"(\d+)")

In [39]:
df_clean["Toilets"] = pd.to_numeric(df_clean["Toilets"], errors="coerce")

In [40]:
df_clean.dtypes

Title              str
More Info          str
Location           str
Price          float64
Serviced         int64
Newly Built      int64
Furnished        int64
Bedrooms       float64
Bathrooms      float64
Toilets        float64
dtype: object

In [41]:
df_clean[["Price", "Bedrooms", "Bathrooms", "Toilets"]].isnull().sum()

Price         855
Bedrooms     3172
Bathrooms    4581
Toilets      4575
dtype: int64

In [42]:
df_clean = df_clean.dropna(subset=["Price"])

In [43]:
df_clean.shape

(97225, 10)

In [44]:
df_clean["Bedrooms"].median()

np.float64(2.0)

In [45]:
df_clean["Bedrooms"] = df_clean["Bedrooms"].fillna(df_clean["Bedrooms"].median())

In [46]:
df_clean["Bathrooms"] = df_clean["Bathrooms"].fillna(df_clean["Bathrooms"].median())

In [47]:
df_clean["Toilets"] = df_clean["Toilets"].fillna(df_clean["Toilets"].median())

In [48]:
df_clean[["Price", "Bedrooms", "Bathrooms", "Toilets"]].isnull().sum()

Price        0
Bedrooms     0
Bathrooms    0
Toilets      0
dtype: int64

In [49]:
df_clean.to_csv("../data/processed/rent_clean_v2.csv", index=False)